/* action types */
export const PLATFORM_ADD = 'PLATFORM_ADD';
export const SET_HOME_PLATFORM = 'SET_HOME_PLATFORM';
export const FETCH_PLATFORM = 'FETCH_PLATFORM';
export const RECEIVE_PLATFORMS = 'RECEIVE_PLATFORMS';
export const PLATFORMS_FETCH_FAILED = 'PLATFORMS_FETCH_FAILED';
export const UPDATE_PLATFORM = 'UPDATE_PLATFORM';
export const DELETE_PLATFORM = 'DELETE_PLATFORM';
export const LOAD_PLATFORM_DATA = 'LOAD_PLATFORM_DATA';

export const ADD_AVATAR = 'ADD_AVATAR';
export const FETCH_AVATAR = 'FETCH_AVATARS';
export const NEXT_AVATAR = 'NEXT_AVATAR';
export const PREVIOUS_AVATAR = 'PREVIOUS_AVATAR';
export const RECEIVE_AVATARS = 'RECEIVE_AVATARS';
export const FAILED_FETCH_AVATARS = 'FAILED_FETCH_AVATARS';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const DELETE_AVATAR = 'DELETE_AVATAR';

export const TRACK_ADD = 'TRACK_ADD';
export const FETCH_TRACK = 'TRACKS_FETCH';
export const TRACKS_FETCH_DONE = 'TRACKS_FETCH_DONE';
export const TRACKS_FETCH_FAIL = 'TRACKS_FETCH_FAIL';
export const UPDATE_TRACK = 'UPDATE_TRACK';
export const DELETE_TRACK = 'DELETE_TRACK';

export const COMPONENT_ADD = 'COMPONENT_ADD';
export const APPEND_COMPONENT = 'APPEND_COMPONENT';
export const FETCH_COMPONENT = 'COMPONENTS_FETCH';
export const COMPONENTS_FETCH_DONE = 'COMPONENTS_FETCH_DONE';
export const COMPONENTS_FETCH_FAILED = 'COMPONENTS_FETCH_FAILED';
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';

export const ADD_ROUTER = 'ADD_ROUTER';
export const FETCH_ROUTER = 'FETCH_ROUTERS';
export const RECEIVE_ROUTERS = 'RECEIVE_ROUTERS';
export const FAILED_FETCH_ROUTERS = 'FAILED_FETCH_ROUTERS';
export const UPDATE_ROUTER = 'UPDATE_ROUTER';
export const DELETE_ROUTER = 'DELETE_ROUTER';

export const USER_ADD = 'USER_ADD';
export const USER_CONNECT = 'USER_CONNECT';
export const USER_DISCONNECT = 'USER_DISCONNECT';
export const USERS_FETCH = 'USERS_FETCH';
export const USERS_FETCH_DONE = 'USERS_FETCH_DONE';
export const USERS_FETCH_FAIL = 'USERS_FETCH_FAIL';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const LOGIN_FETCH = 'LOGIN_FETCH';
export const LOGIN_DONE = 'LOGIN_DONE';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ADD_NPC = 'ADD_NPC';
export const FETCH_NPC = 'FETCH_NPCS';
export const RECEIVE_NPCS = 'RECEIVE_NPCS';
export const FAILED_FETCH_NPCS = 'FAILED_FETCH_NPCS';
export const UPDATE_NPC = 'UPDATE_NPC';
export const DELETE_NPC = 'DELETE_NPC';

export const ADD_PATTERN = 'ADD_PATTERN';
export const FETCH_PATTERNS = 'FETCH_PATTERNS';
export const RECEIVE_PATTERNS = 'RECEIVE_PATTERNS';
export const FAILED_FETCH_PATTERNS = 'FAILED_FETCH_PATTERNS';
export const UPDATE_PATTERN = 'UPDATE_PATTERN';
export const DELETE_PATTERN = 'DELETE_PATTERN';
export const NEXT_PATTERN = 'NEXT_PATTERN';
export const PREVIOUS_PATTERN = 'PREVIOUS_PATTERN';
export const SELECT_PATTERN = 'SELECT_PATTERN';

export const TOOL_ADD = 'TOOL_ADD';
export const FETCH_TOOLS = 'FETCH_TOOLS';
export const RECEIVE_TOOLS = 'RECEIVE_TOOLS';
export const FAILED_FETCH_TOOLS = 'FAILED_FETCH_TOOLS';
export const UPDATE_TOOL = 'UPDATE_TOOL';
export const DELETE_TOOL = 'DELETE_TOOL';
export const NEXT_TOOL = 'NEXT_TOOL';
export const PREVIOUS_TOOL = 'PREVIOUS_TOOL';

export const ENTITY_ADD = 'ENTITY_ADD';
export const ENTITIES_FETCH = 'ENTITIES_FETCH';
export const ENTITIES_FETCH_DONE = 'ENTITIES_FETCH_DONE';
export const ENTITIES_FETCH_FAILED = 'ENTITIES_FETCH_FAILED';
export const UPDATE_ENTITY = 'UPDATE_ENTITY';
export const DELETE_ENTITY = 'DELETE_ENTITY';
export const SELECT_ENTITY = 'SELECT_ENTITY';

export const ADD_PAGE = 'ADD_PAGE';
export const FETCH_PAGE = 'FETCH_PAGE';
export const PAGES_FETCH_DONE = 'PAGES_FETCH_DONE';
export const PAGES_FETCH_FAIL = 'PAGES_FETCH_FAIL';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const DELETE_PAGE = 'DELETE_PAGE';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
export const FAILED_FETCH_MESSAGES = 'FAILED_FETCH_MESSAGES';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

export const ADD_FILE = 'ADD_FILE';
export const FETCH_FILE = 'FETCH_FILES';
export const RECEIVE_FILES = 'RECEIVE_FILES';
export const FAILED_FETCH_FILES = 'FAILED_FETCH_FILES';
export const UPDATE_FILE = 'UPDATE_FILE';
export const DELETE_FILE = 'DELETE_FILE';
